version: 2.1
orbs:
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - browser-tools/install-chrome
      - run:
          name: Run tests
          command: npm run test

workflows:
  build-and-test:
    jobs:
      - test
